name: Update README.md

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
  schedule:
    - cron: "0 */4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - run: |
        git config user.name rubendiazzz
        git config user.email rubendfraga@gmail.com
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with latest info"
        git push origin master
