name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  push:
    branches: [master]
  schedule:
    # runs at midnight
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this Repo's README.md
    runs-on: ubuntu-latest
    steps:
        # this action name
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required          
          
          ### content
          SHOW_TITLE: true # optional
          SECTION_NAME: waka # optional
          #BLOCKS: -> # optional
          CODE_LANG: rust # optional
          LANG_COUNT: 10 # optional
          TIME_RANGE: all_time
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          SHOW_MASKED_TIME: false # optional
          STOP_AT_OTHER: true # optional
          IGNORED_LANGUAGES: YAML JSON TOML # optional
          ### commit
          #COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
          #TARGET_BRANCH: master # optional
          #TARGET_PATH: README.md # optional
          #COMMITTER_NAME: rubendiazzz # optional
          #COMMITTER_EMAIL: rubendfraga@gmail.com # optional
          #AUTHOR_NAME: Ruben Diaz # optional
          #AUTHOR_EMAIL: rubendfraga@gmail.com # optional
          # you can populate email-id with secretes instead
